### ISSUE TITLE
Does not recognize Samsung Internet Browser

### ISSUE THREAD

**Issue by halukakin** [wangkanai/wangkanai#1006]
### Describe the bug

Reports Chrome when the browser is actually Samsung Internet Browser.

### To Reproduce

Try a user agent like:

Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-A528B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/21.0 Chrome/110.0.5481.154 Mobile Safari/537.36

### Expected behavior

Should return Samsung not Chrome.

**Comment by halukakin** [comment]
This PR resolves the issue:
#1005

**Comment by wangkanai** [comment]
@halukakin 

Thank you very much for reporting this issue, and I much appreciate your pull request contribution. 

Best regards,

Sarin

**Comment by halukakin** [comment]
@wangkanai Glad to help any time. Thank you for paying attention to this issue. 🙏

**Comment by wangkanai** [comment]
This change will be in the next release publish to NuGet
