### ISSUE TITLE
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by jaytarr** [wangkanai/wangkanai#472]
### Describe the bug
In our server logs we are occasionally seeing the following:
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Wangkanai.Detection.Services.BrowserService.GetVersion(String agent, String browser)
   at Wangkanai.Detection.Services.BrowserService..ctor(IUserAgentService userAgentService, IPlatformService platformService, IEngineService engineService)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```

### To Reproduce
This does not happen on every request. I would estimate it to be around 0.5% of requests if that.
We are using .net core 3.1.3
In our controller we are checking to see if the device is a mobile device via `var isMobile = detectionService.Device.Type == Device.Mobile;`.
With the number of devices that are accessing the site, I am wondering if there is a device that is not accounted for.

### Expected behavior
Exception is not thrown

### Screenshots
n/a

### Additional context
Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.514 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by wangkanai** [comment]
@jaytarr interesting error!

This should not even happen because the device default is desktop. Can you help me get the `string` that is causing the error? much appreciated. I hope it would not be another billion dollars `null` exception.  😺

**Comment by zamecnik** [comment]
We are having the very same issue... In our server log there is a lot of exceptions System.ArgumentOutOfRangeException with the very same stack as jaytarr posted. Any update on this please?

**Comment by jaytarr** [comment]
We are still seeing it in 3.0 so we're currently in the process of improving our logging to capture the user-agent and other details. This may allow us to find a pattern and provide the ability to reproduce the error. Perhaps something is not accounted for.

**Comment by zamecnik** [comment]
Thanks @jaytarr... When i took a look at our log, these errors appeared only in one particular day (from morning to night - 2021/03/02) and no users complained... I would quess its gonna by some bot maybe?

**Comment by jaytarr** [comment]
@wangkanai We have implemented additional logging to capture the user-agent when this exception is thrown.  In every single instance of this exception (and we get multiple per day), the user-agent is either `Ruby` or `curb`.  These are likely bots of some sort, but should still be handled gracefully.  Does this help?

![image](https://user-images.githubusercontent.com/27645735/111835059-d730c100-88ca-11eb-9b33-7c1eb503e9b9.png)

![image](https://user-images.githubusercontent.com/27645735/111835092-e31c8300-88ca-11eb-89c8-be8ecfa9ba07.png)

**Comment by SerkanTopkan** [comment]
This error occurs for me too.

**Comment by zamecnik** [comment]
Would be great to take a look at, its really bloating our log.

**Comment by MichaelSL** [comment]
@wangkanai it seems like you already have the fix that addresses this issue in the `main` branch. Do you plan to release a new version of a nuget package or build a preview package from `main` branch?

**Comment by wangkanai** [comment]
let me have a look if there are any bugs in the main branch

**Comment by MichaelSL** [comment]
@wangkanai  thank you!

**Comment by siyo-wang** [comment]
信已收到
