### ISSUE TITLE
More Details.

### ISSUE THREAD

**Issue by SerkanTopkan** [wangkanai/Wangkanai#484]
Can I get more details about these parameters please.
options.IdleTimeout = TimeSpan.FromSeconds(10);
        options.Cookie.HttpOnly = true;
        options.Cookie.IsEssential = true;

**Comment by wangkanai** [comment]
Hi @SerkanTopkan 

What kind of more details for the above paramaters? like the usage in the Responsive of the session service right?

**Comment by wangkanai** [comment]
Please revisit this issue. Because Responsive 3.0 has now been remove from Detection 5.0
