### ISSUE TITLE
Specified argument was out of the range of valid values. (Parameter 'i') 

### ISSUE THREAD

**Issue by dovizmix** [wangkanai/wangkanai#502]
### To Reproduce
1. Using this version of ASP.NET Core 3.1'
2. Detection Version 3.0
Methot : -GET 
Protokol : HTTP/1.1 
User Agent : Reeder-P10/V1 Linux/3.10.65+ Android/5.1 Release/05.19.2016 Browser/AppleWebKit537.36 Chrome/39.0.0.0 Mobile Safari/537.36 System/Android 5.1;
Exception = Specified argument was out of the range of valid values. (Parameter 'i') - /haber/atom-coin-yorum-gelecegi-fiyat-grafik-ve-haberleri  at System.Text.RegularExpressions.CaptureCollection.GetCapture(Int32 i)

**Comment by jorgepsmatos** [comment]
This seems related with issue https://github.com/wangkanai/Detection/issues/499
