### ISSUE TITLE
Why you have dependency on Session? I can't use it in .NET 6 Project

### ISSUE THREAD

**Issue by nssidhu** [wangkanai/Wangkanai#504]
### To Reproduce
1. Using this version of ASP.NET Core '...'
2. Run this code '....'
3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by wangkanai** [comment]
Session is use in Responsive feature. I will review this again for .NET 6 compatibility

**Comment by nssidhu** [comment]
FYI, i was trying to use it in .NET 6 Minimal API

**Comment by vankampenp** [comment]
I am using it without Session. But I am not using the responsive feature.

**Comment by nssidhu** [comment]
Got it, but adding additional Razor libraries is also an hurdle as it is adding unnecessary clutter. mine is pure api.
Are these additional razor libraries needed for the detection ?
![image](https://user-images.githubusercontent.com/3267605/144352416-fea39f16-7e6c-4609-a381-1eec293c36c9.png)

**Comment by wangkanai** [comment]
`Wangkanai.Detection` for upcoming 5.0 release will split Responsive from Detection. This release will be built for .NET 6.0, which would have a lot of break changes in library. So be prepare for the changes.

**Comment by wangkanai** [comment]
I have you tried the new 5.0 development yet?

**Comment by siyo-wang** [comment]
信已收到

**Comment by nssidhu** [comment]
no  not yet
    On Tuesday, 7 December, 2021, 07:33:44 pm GMT-6, Sarin Na Wangkanai ***@***.***> wrote:  
 
 


I have you tried the new 5.0 development yet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangkanai** [comment]
Responsive 3.0 has now be remove from Detection 5.0 for .NET 6.0 release, feel free to try it out @nssidhu .
