### ISSUE TITLE
Opera detects as Chrome due to wrong UA expected

### ISSUE THREAD

**Issue by TeKi9001** [wangkanai/Wangkanai#508]
Since v15 Opera uses 'OPR' in UA header instead of 'Opera', and now it's always detected as Chrome (which is not far from the truth). 
Example header:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 OPR/82.0.4227.33 (Edition Yx 03)

https://dev.opera.com/blog/opera-user-agent-strings-opera-15-and-beyond/

**Comment by wangkanai** [comment]
Completed with detection 5.0
