### ISSUE TITLE
iPadOS - Apple typo causes detection as version zero

### ISSUE THREAD

**Issue by Phoniexk** [wangkanai/wangkanai#567]
Some time ago Apple has released a new iPadOS 15.7. They have a typo in their version number: **version/15.6,2** (they used a comma instead a dot). Your browser detection reports safari version zero.

user agents to reproduce (taken from wangkanai detection plugin):

Page requested for desktop-view (user-agent act like a macOS)
>mozilla/5.0 (macintosh; intel mac os x 10_15_6) applewebkit/605.1.15 (khtml, like gecko) version/15.6,2 safari/605.1.15

Page requested as mobile-view
>mozilla/5.0 (ipad; cpu os 15_7 like mac os x) applewebkit/605.1.15 (khtml, like gecko) version/15.6,2 mobile/15e148 safari/604.1

Screenshot of wangkanai detection:
![grafik](https://user-images.githubusercontent.com/19604967/195981112-b8e63fbd-b446-44c3-a0dd-230bb0240b35.png)

**Comment by wangkanai** [comment]
Thank you for the heads up, i will have a look at this afternoon.

**Comment by wangkanai** [comment]
I can't find any reference to such user agent anywhere. Are you sure that is correct?

But in the meantime, I add an extra condition to parse the version. See would this work for you for now.

**Comment by Phoniexk** [comment]
I don‘t know if this issue (of Apple) is caused by specific country/language settings (German) or if is generally. I have attached a screenshot of my iPadOS version and the user agent from a public service.

The user agent can be reproduced on multiple devices (friends, family and customers). 

I will try your fix later.

![6ADB8D91-672A-4449-B9D3-2185B238E201](https://user-images.githubusercontent.com/19604967/196048007-3cdff06c-d0c7-492a-9d24-8ea27a82a786.jpeg)
![1C69C889-F19A-47BB-8B23-390FA1C4A107](https://user-images.githubusercontent.com/19604967/196048011-b90294c7-ae85-4850-9c01-60e78a327408.png)
![F255B721-18D7-470F-AA72-CC3FB43B6057](https://user-images.githubusercontent.com/19604967/196048017-18efae35-c510-45e2-84b4-7cb134e75ea0.png)

**Comment by Phoniexk** [comment]
I have tried you fix with version 5.7.3 and it is working now. Thank you for the immediate fix.

**Comment by wangkanai** [comment]
You are welcome, I will keep this issue open until we find more reference sources to make this a permanent fix for report as iPadOS 15.7

**Comment by wangkanai** [comment]
I have tried my iPad Pro with 15.7 and find the same results for safari, but not in google chrome. So this is a much more like a web browser issue. But anyway, I will leave this open for about another month and see how it goes. If I should a make special condition for safari in iPadOS 15.7

If you can help get for your friends and/or challenge to report and contribute to this issue, for us to speed this up.

![image](https://user-images.githubusercontent.com/10666633/196067770-7628801c-7233-40d9-8255-b01e902b5901.png)

![image](https://user-images.githubusercontent.com/10666633/196067790-d8579982-c04a-4451-a744-3c66e568c2a6.png)

**Comment by wangkanai** [comment]
No report of any issue about this issue. I so will close this issue for now.
