### ISSUE TITLE
viewname.Mobile.cshtml views no longer used after upgrading from .NET Core 3.1 to .NET 7 and latest Detection version

### ISSUE THREAD

**Issue by 64Soft** [wangkanai/wangkanai#577]
### Describe the bug
- Updated an ASP.NET Core MVC 3.1 app to .NET Core MVC 7. 
- Updated Wangkanai.Detection from 3.0.0-alpha05 to 6.2.0
- Moved app.UseDetection() before app.UseRouting() as required

When I inject IDetectionService in a controller, and emulate with Chrome a mobile device, I can clearly see it detects my device as type "Mobile", that's fine.

However, in the controller action (Index) I do 

`return View();`

but it no longer uses the Mobile view (Index.Mobile.cshtml), but instead uses the regular view (Index.html).

### Expected behavior
I expected it would use the viewname.Mobile.cshtml views as it did in .NET Core 3.1 and Wangkanai.Detection 3.0.0-alpha05

**Comment by wangkanai** [comment]
Oh, you would need to have `Wangkanai.Responsive` install for that features. This has been seperate a while back already.

For more information please reference to

https://github.com/wangkanai/wangkanai/tree/main/Responsive

I hope this would you.

**Comment by 64Soft** [comment]
oh I see, thanks for the info

**Comment by wangkanai** [comment]
Your welcome
