### ISSUE TITLE
Wangkanai.Detection does not log Opera browser properly

### ISSUE THREAD

**Issue by orrishu** [wangkanai/wangkanai#645]
### Is your feature request related to a problem? Please describe.
Hi, I use Wangkanai.Detection to log browser requests on the api backend of a website.
However, it detects Opera browser as Chrome, and does not log it as Opera.

### Describe the solution you'd like
If possible :) can you add detection of Opera browser? 
I guess this is not an urgent issue, but it can be helpful.

### Describe alternatives you've considered
None

### Additional context
The current user agent for Opera is:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 OPR/96.0.0.0`

I am really fond of this project, thanks in advance ❤

**Comment by wangkanai** [comment]
Thank you for the heads up, I will have a detail look at it tomorrow.

**Comment by wangkanai** [comment]
Surely, I will have a look into the browser version issue.

**Comment by wangkanai** [comment]
> Hi, @wangkanai thanks a lot for the fix! Now I get the Opera browser name properly, however, the browser version returns as 0.0 . I wonder if you can also fix this small issue, if you have some spare time :) Thanks in advance 😊

I have fixed this issue and going to publish a update release to nuget with version 7.1.1
