### ISSUE TITLE
WangKanai.com is down?

### ISSUE THREAD

**Issue by Zerthz** [wangkanai/wangkanai#650]
### Describe the bug
I click the link to wangkanai.com and I get hit with a 404 no site found from GitHub Pages. Also tried using Edge incase it was some weird Firefox thing. Still didn't work

### To Reproduce
Go to WangKanai.com

### Expected behavior
I haven't been there before, but I expect to be brought to a landing page not a 404 page.

### Screenshots
[Image](https://i.imgur.com/hVDqByl.png)

**Comment by wangkanai** [comment]
I'm planning to redeploy it soon with asp.net core web app in the https://github.com/wangkanai/wangkanai/tree/main/Web

**Comment by Zerthz** [comment]
Makes sense! Good luck :)
