### ISSUE TITLE
Add support for detecting Edge on Android

### ISSUE THREAD

**Issue by ricardoboss** [wangkanai/wangkanai#954]
### Is your feature request related to a problem? Please describe.

The browser is incorrectly detected as "Chrome".

### Describe the solution you'd like

The browser should be detected as "Edge".

### Describe alternatives you've considered

-

### Additional context

The user agents for Edge on Windows and Edge on Android are similar, but not quite the same:

Edge on Windows:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
```

Edge on Android:
```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36 EdgA/120.0.0.0
```

Notice the `EdgA` instead of `Edg` at the end.

**Comment by wangkanai** [comment]
Todo later

**Comment by siyo-wang** [comment]
信已收到
